actitvemq.url = failover://(tcp://activeMq:61616)?initialReconnectDelay=3000&maxReconnectAttempts=2
response.topic = RESPONSE.TOPIC
request.queue = REQUEST.QUEUE
redis.host = redis
redis.port = 6379
actitvemq.connection.number = 2
actitvemq.connection.thread = 4
# lets make easy test in multithreading works
actitvemq.prefetch = 1
shutdown.port = 6347